### ISSUE TITLE
LastTransitionTime for a Condition is supposed to represent when the Status of that Condition changed

### ISSUE THREAD

**Issue by juliev0** [numaproj/numaplane#107]
**Describe the bug**
Currently, we update a Condition's `LastTransitionTime` even when the Condition didn't change. 

According to the [documentation](https://github.com/kubernetes/apimachinery/blob/master/pkg/apis/meta/v1/types.go#L1554) for `Condition`, it should be updated only when the Status changes.

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We often sort issues this way to know what to prioritize.

**Comment by xdevxy** [comment]
This is a valid concern. So instead of playing with `LastTransitionTime`, let's only mark the deployed condition when there there is a new deployment ( which is the generation does not match with observedGeneration).

**Comment by juliev0** [comment]
> This is a valid concern. So instead of playing with `LastTransitionTime`, let's only mark the deployed condition when there there is a new deployment ( which is the generation does not match with observedGeneration).

So, in this scenario:
1. HealthyCondition.value == true, Generation=9
2. Generation changes to 10
3. HealthyCondition.value still equals true at time 1:00:00

then I believe you want the `HealthyCondition.ObservedGeneration` to equal 10, right? And what do you want `HealthyCondition.LastTransitionTime` to be? 1:00:00 or the last time that it changed from `HealthyCondition.value==false` to `true`? From the documentation, it seems like it would be the latter, right?

**Comment by afugazzotto** [comment]
@xdevxy @juliev0 based on the description of [this field](https://github.com/kubernetes/apimachinery/blob/master/pkg/apis/meta/v1/types.go#L1560), do you think we should update the `LastTransitionTime` only if the `Status` of the condition changes value or even in case of changes to `Reason`, `Message`, `ObservedGeneration`?

**Comment by xdevxy** [comment]
> @xdevxy @juliev0 based on the description of [this field](https://github.com/kubernetes/apimachinery/blob/master/pkg/apis/meta/v1/types.go#L1560), do you think we should update the LastTransitionTime only if the Status of the condition changes value or even in case of changes to Reason, Message, ObservedGeneration?

I feel it should include changs of `Reason`, `Message`, `ObservedGeneration` these also indicate status change even though the `Status` field value may remain the same.

> From the documentation, it seems like it would be the latter, right?

@juliev0  I think it should be 1:00:00, even though condition status value did not change, but it is a new state which happens after the latest deployment.

**Comment by juliev0** [comment]
> > @xdevxy @juliev0 based on the description of [this field](https://github.com/kubernetes/apimachinery/blob/master/pkg/apis/meta/v1/types.go#L1560), do you think we should update the LastTransitionTime only if the Status of the condition changes value or even in case of changes to Reason, Message, ObservedGeneration?
> 
> I feel it should include changs of `Reason`, `Message`, `ObservedGeneration` these also indicate status change even though the `Status` field value may remain the same.
> 
> > From the documentation, it seems like it would be the latter, right?
> 
> @juliev0 I think it should be 1:00:00, even though condition status value did not change, but it is a new state which happens after the latest deployment.

To me, it seems like the `LastTransitionTime` should represent the time in which the value (which could include the true/false value or the `Reason`) changed. Can we find out how things like `Deployment` are using it? (The controllers for those core objects are [here](https://github.com/kubernetes/kubernetes/tree/master/pkg/controller))

**Comment by afugazzotto** [comment]
These are some pieces of code about how Deployments conditions are updated:
https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/deployment/sync.go#L512

https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/deployment/util/deployment_util.go#L104

https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/deployment/util/deployment_util.go#L128

Note that they have 2 timestamps: `LastTransitionTime` and `LastUpdateTime`.
Also note that they only account for the `Status` and not `Reason` or other fields to update `LastTransitionTime`: https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/deployment/util/deployment_util.go#L133C19-L133C38

**Comment by xdevxy** [comment]
yeah, I agree with you @juliev0 in this case, only check status and reason change. as the way we are doing should be actually tracked as `LastUpdateTime`.
