### ISSUE TITLE
e2e framework - CRUD + Self Healing

### ISSUE THREAD

**Issue by juliev0** [numaproj/numaplane#110]
# Summary

create reusable functionality both within e2e test and shared with unit tests

# Use Cases

When would you use this?

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by afugazzotto** [comment]
Make sure to verify if the dynamic client could be used for both e2e and unit tests and what functions could be really shared.
