### ISSUE TITLE
Support PipelineRollouts in which user sets lifecycle field

### ISSUE THREAD

**Issue by juliev0** [numaproj/numaplane#113]
# Summary

In the current code we make an assumption that user isn't explicitly setting "lifecycle" field. But they could be. If they are setting "lifecycle" to "paused", then we should make sure we leave the Pipeline paused after the update. If they are setting it to "running", then if the update requires pausing, we still make sure we pause as usual during the update.

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by xdevxy** [comment]
This is already supported
