### ISSUE TITLE
Ensure draining is always complete with best effort 

### ISSUE THREAD

**Issue by xdevxy** [numaproj/numaplane#124]
# Summary

We need to make the default value as unlimited or large time (e.g. 30 mins) to always wait for the draining is complete or timeout in upper level. 

Optionally We may want to provide an option to indicate some of the pipeline may needs longer time to complete drain as numaflow has such option via `spec.lifecycle.pauseGracePeriodSeconds.`

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by juliev0** [comment]
I wonder if it makes sense for Numalego to provide that option and then they include it in the Rollout's Pipeline Spec directly?

**Comment by juliev0** [comment]
Discussed with Derek and we agreed that within Intuit we can have a larger value by default - this can be indicated on the Paved Path side. I will write up an issue there

**Comment by juliev0** [comment]
https://github.intuit.com/oss-analytics/numaportal/issues/301

**Comment by xdevxy** [comment]
Close this as it duplicates https://github.com/numaproj/numaplane/issues/74
