### ISSUE TITLE
Refactor: Avoid too many conversions between GenericObject, Unstructured, PipelineSpec

### ISSUE THREAD

**Issue by juliev0** [numaproj/numaplane#143]
# Summary

I'm thinking maybe we could at the beginning of reconciliation create a struct which can include all the various forms of our current child object and our desired object. Then we could pass that into the various functions, without having to repeatedly do the same translations over and over. 

For the Pipeline, we sometimes use:

- GenericObject
- [PipelineSpec ](https://github.com/numaproj/numaplane/blob/v0.5.0/internal/controller/pipelinerollout_controller.go#L68), which contains just the fields we need that should not ever change
- [GenericStatus](https://github.com/numaproj/numaplane/blob/v0.5.0/internal/util/kubernetes/unstructured_util.go#L34) 
- we don't have a `PipelineStatus` at the moment, but I think we will need it for fields that are not in `GenericStatus`
- `map[string]interface{}`  

For the isbsvc and monovertex, we could theoretically do the same.

For each of them, at the beginning of the reconciliation we create a `GenericObject` from the existing object that we find in Kubernetes and we create another `GenericObject` from the new one based on the Rollout. Then we make modifications to it for example to update the `desiredPhase` field. 

For both "new" and "existing", I'd like to be able to create a single Object at the beginning that stores any of the forms we may need. And if I need to update the "new" one, it should update all of the forms. 

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by chandankumar4** [comment]
I'm checking the feasibility to completely eliminate the `kubernetes.GenericObject` struct and directly work on `unstructured.Unstructured`, So that we don't need any conversion in between. If it's not possible then probably I'll work on design to make the conversion in more efficient way. How it's sound?
