### ISSUE TITLE
Recreate ISBService during upgrade

### ISSUE THREAD

**Issue by xdevxy** [numaproj/numaplane#147]
# Summary

Jetstream may have backward incompatible issue, so 1) we may need to recreate ISBService during upgrade instead of spec apply.  Later, 2) we can see how to optimize for different versions by working with upgrade detect engine.

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by afugazzotto** [comment]
This should be milestone 2. For now we Pause and Drain.

**Comment by xdevxy** [comment]
Close this as https://github.com/numaproj/numaplane/issues/181 should cover this when it is done.
