### ISSUE TITLE
Emit K8s events for major events

### ISSUE THREAD

**Issue by vigith** [numaproj/numaplane#153]
# Summary

If we are logging major events, we should also emit K8s events so we can see those in `kubectl get events` command

# Use Cases

Debugging and monitoring

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by xdevxy** [comment]
This events should include both system and user namespace.
