### ISSUE TITLE
Enable dynamic modification of DataLossPrevention feature flag

### ISSUE THREAD

**Issue by juliev0** [numaproj/numaplane#155]
# Summary

Currently Feature flag is only read on start up. If we modify it to be dynamically modifiable, then we could modify it on all clusters and not require the Pods to be restarted.

# Use Cases

When would you use this?

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by xdevxy** [comment]
@juliev0 I think we should prioritize on https://github.com/numaproj/numaplane/issues/170 instead of this

**Comment by juliev0** [comment]
I am closing this issue altogether, as I believe the feature flag will be replaced by the new namespace level configurability. If you think it should be reopened, let me know.

**Comment by juliev0** [comment]
reopening this since it sounds like we will use both concurrently for a little while

**Comment by juliev0** [comment]
We can check the value each time either the PipelineRollout or the NumaflowControllerRollout or ISBServiceRollout reconcile occurs.

I've done a little thought to the scenario that something's in the middle of pausing when we turn the feature flag off. What would happen? (The reverse case of turning the feature flag on is definitely no issue)

```
if we suddenly turn feature flag off:
	what happens to Pipeline?:
		say Pipeline was paused because of us
		if we notice a difference between existing pipeline and pipeline we want (Running) then we will apply (may take 12 minutes)

	what happens to Numaflow Controller?:
		say Pipelines were paused because of us
		this means that our state in memory reflects that we "want pause". 
		Once feature flag is off, Pipelines will notice a difference between existing pipeline and pipeline spec and perform an update (may take 12 minutes)

		What happens if the feature flag is turned back on? There is old memory still in there. Say it says "pause" and we don't want that. At some point, the Numaflow Controller Rollout will get reconciled, so this will reflect the truth.
```

**Comment by juliev0** [comment]
closing this as this feature flag has been replaced
