### ISSUE TITLE
Perform FMEA testing for Numaplane with dataLossPrevention = false

### ISSUE THREAD

**Issue by xdevxy** [numaproj/numaplane#158]
# Summary

Cover FMEA for testing availability, reliability. 

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by juliev0** [comment]
FYI @xdevxy I broke this issue into two, one for the feature flag turned on and one for it turned off. I assigned @chandankumar4 to this one and myself to the [other](https://github.com/numaproj/numaplane/issues/165).

**Comment by juliev0** [comment]
now that we will primarily be doing PPND, we can probably not do this I'm thinking
