### ISSUE TITLE
Namespace scope of control on draining for upgrade at runtime 

### ISSUE THREAD

**Issue by xdevxy** [numaproj/numaplane#170]
# Summary

We should support Namespace scope flag to enable/disable draining for no data loss upgrade at runtime.

# Use Cases

Instead of cluster level flag control the draining for no data loss upgrade feature, we should have runtime config to turn it on/off at namespace level.

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by juliev0** [comment]
@afugazzotto should this be in current sprint? I believe you are doing it now maybe?

**Comment by afugazzotto** [comment]
@juliev0 I think this is related to the user strategy selection done at the namespace level. If that is the case, this is duplicate and I have already done that task.

**Comment by juliev0** [comment]
closing as duplicate, thanks
