### ISSUE TITLE
Flag to indicate user intention on pausing a pipeline

### ISSUE THREAD

**Issue by xdevxy** [numaproj/numaplane#171]
# Summary

We need to provide a way to distinguish user intention on pausing a pipeline from platform needs to draining for no data loss upgrade when the feature flag is on.

# Use Cases

We want to support the case user wants to explicitly pausing the pipeline.

- [ ] #113 

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by xdevxy** [comment]
@juliev0

**Comment by juliev0** [comment]
I am closing this, as it seems this was written back when we intended on having per-pipeline control instead of per-namespace control, which is in [this](https://github.com/numaproj/numaplane/issues/170) issue

**Comment by juliev0** [comment]
see comment [here](https://github.com/numaproj/numaplane/issues/136#issuecomment-2253750785)

Will also include in FMEA testing just to be sure. Have added it to spreadsheet of tests [here](https://docs.google.com/spreadsheets/d/10vmyumoJuMtKIbQ5H7gEN7ROaXIAoplAoZ84G61OIA0/edit?gid=0#gid=0)
