### ISSUE TITLE
USDE: Analyze more fields of Pipeline to improve USDE comparison

### ISSUE THREAD

**Issue by afugazzotto** [numaproj/numaplane#181]
# Summary

Figure out what fields could be added to the exclusion list by looking at second level and lover levels of the Pipeline spec. 

File [here](https://github.com/numaproj/numaplane/blob/main/config/manager/usde-config.yaml)

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by juliev0** [comment]
this is done
