### ISSUE TITLE
auto heal for NumaflowControllerRollout

### ISSUE THREAD

**Issue by xdevxy** [numaproj/numaplane#19]
Watch() NumaflowController Deployment and related resources to trigger Reconcile() like we do with PipelineRollout and ISBServiceRollout. https://github.com/numaproj/numaplane/issues/6 is an improvements we can consider later.

**Comment by juliev0** [comment]
> https://github.com/numaproj/numaplane/issues/6 is an improvements we can consider later.

Hi @xdevxy. Can you clarify what makes this option too complicated? As far as I could tell, in the original code, there was a placeholder for that, no?
