### ISSUE TITLE
ArgoCD health check should consider "PipelinesPausingOrPaused" Condition for ISBServiceRollout, NumaflowControllerRollout

### ISSUE THREAD

**Issue by juliev0** [numaproj/numaplane#224]
**Describe the bug**

For PPND strategy, user will try to update Numaflow Controller or ISBService, which will initially cause pipelines to pause. ArgoCD should probably indicate "Progressing" while this is happening. 

[NumaflowControllerRollout health check](https://github.com/argoproj/argo-cd/blob/master/resource_customizations/numaplane.numaproj.io/NumaflowControllerRollout/health.lua)
[ISBServiceRollout health check](https://github.com/argoproj/argo-cd/blob/master/resource_customizations/numaplane.numaproj.io/ISBServiceRollout/health.lua)

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We often sort issues this way to know what to prioritize.

**Comment by xdevxy** [comment]
Closed this one as @dpadhiar already verify the ISBServiceRollout, NumaflowControllerRollout is progressing while pipeline pausing
