### ISSUE TITLE
Add Rollout Health Metrics 

### ISSUE THREAD

**Issue by xdevxy** [numaproj/numaplane#233]
# Summary

We should add Rollout Health Metrics for each type using the phase information in status.

# Use Cases

Health metrics will be used for incident indication.

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by chandankumar4** [comment]
I had thought about the implementation about it, where the metrics data should looks like below, But if the phase changes then it will be a new metrics all together will be become problem.
```
numaplane_rollout_health_status{intuit_alert="true",phase="Deployed",type="isbservice-rollout-controller"} 0
numaplane_rollout_health_status{intuit_alert="true",phase="Deployed",type="pipeline-rollout-controller"} 0
numaplane_rollout_health_status{intuit_alert="true",phase="Deployed",type="numaflow-controller-rollout-controller"} 0
```

**Comment by xdevxy** [comment]
We can refer to how numaflow is adding the health [metrics](https://github.com/numaproj/numaflow/blob/main/pkg/reconciler/metrics.go#L35-L46).
