### ISSUE TITLE
PPND strategy needs to allow there to be Pipelines not owned by a PipelineRollout

### ISSUE THREAD

**Issue by juliev0** [numaproj/numaplane#245]
**Describe the bug**
Currently, NumaflowControllerRollout recociler presumes that any Pipelines in its namespace are owned by a PipelineRollout. ISBServiceRollout reconciler assumes that any Pipelines on the isbsvc are owned by a PipelineRollout as well.

They will wait for all of these Pipelines to pause; however any Pipeline not owned by a PipelineRollout will never be told this and so it will never pause.

Therefore, we should fix the calls ([here](https://github.com/numaproj/numaplane/blob/v0.5.0/internal/controller/numaflowcontrollerrollout_controller.go#L332) and [here](https://github.com/numaproj/numaplane/blob/v0.5.0/internal/controller/isbservicerollout_controller.go#L366)) to only look for those which are labeled with a PipelineRollout label. (we need to add that label if it's not already there by the time this gets worked on)

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We often sort issues this way to know what to prioritize.

**Comment by juliev0** [comment]
thought you may be able to help out with this one later @dpadhiar ?

**Comment by dpadhiar** [comment]
> thought you may be able to help out with this one later @dpadhiar ?

Ack, can take this up when I am finished with current tasks or time provides.
