### ISSUE TITLE
Investigate if ArgoCD UI extension support write operation

### ISSUE THREAD

**Issue by xdevxy** [numaproj/numaplane#282]
# Summary

We'd like to investigate if ArgoCD UI extension support write operation so that user can use it to perform actions that would result in rollout spec changes. For example, pause feature that would change the `lifecycle.desiredPhase` field to be `paused`. 

Also, we'd like to understand how ArgoCD do the gitops comparison, so that whether such in cluster change would trigger ArgoCD to consider the service is out of sync or not.

# Use Cases

Support instant in cluster rollout spec write to enable features as pause a pipeline or monovertex.

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by dpadhiar** [comment]
Investigation concluded -  found that when updating a Rollout spec using k8s instead of GitOps that ArgoCD did not go out of sync. Moving forward with creating pause action for extension in #293
