### ISSUE TITLE
Define custom health check for Rollout resources in Argo CD

### ISSUE THREAD

**Issue by xdevxy** [numaproj/numaplane#29]
# Summary

Define custom health status check in ArgoCD for NumaRollout CRs to incorporate the status of underlying Numaflow CRs. There are two ways to do [that](https://argo-cd.readthedocs.io/en/stable/operator-manual/health/#custom-health-checks), need to figure out which one is the best suitable one.

# Use Cases

We need to define health check scripts for NumaRollout resources including `PipelineRollout`, `ISBServiceRollout` and `NumaflowControllerRollout`, so that the healthiness of underlying Numaflow resources are truly reflected.

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by afugazzotto** [comment]
Could [this](https://github.com/afugazzotto/ged24-demo/blob/main/resources/argocd-setup/configmap.yaml#L10) help?

**Comment by juliev0** [comment]
@dpadhiar So, the health check indicates to ArgoCD how to indicate the health of each type of CRD on the UI. Hao wrote up [this](https://docs.google.com/document/d/1llAM4RL6t8FCpAWVUwJCeKd3WNZ_vr0OqJ29OmUxm_c/edit#heading=h.4blxmikcdlg) document on how our Status would be for the various Rollout objects and @afugazzotto wrote the corresponding [code](https://github.com/numaproj/numaplane/pull/92/files).

Based on that, we're thinking you should be able to set up ArgoCD locally - maybe create a fork or something off of @afugazzotto 's GED [repo](https://github.com/afugazzotto/ged24-demo/tree/main). He has a nice README.md there to walk through setting everything up. The [lua script ](https://github.com/afugazzotto/ged24-demo/blob/main/resources/argocd-setup/configmap.yaml#L10) he has there would need to change based on our latest Status values. 

Once you have this tested locally, we can provide the lua script to Michael Crenshaw to add to the ArgoCD ConfigMap `argocd-cm` per [this](https://intuit-teams.slack.com/archives/C076W26LMPT/p1717540481636909) thread.

**Comment by juliev0** [comment]
Note, ArgoCD has these values per [this](https://argo-cd.readthedocs.io/en/stable/operator-manual/health/#custom-health-checks) link:
```
Healthy - the resource is healthy
Progressing - the resource is not healthy yet but still making progress and might be healthy soon
Degraded - the resource is degraded
Suspended - the resource is suspended and waiting for some external event to resume (e.g. suspended CronJob or paused Deployment)
```

We should use all of those. "Paused" fits into "Suspended"

**Comment by dpadhiar** [comment]
Upstream PR has been merged on ArgoCD: https://github.com/argoproj/argo-cd/pull/19077
