### ISSUE TITLE
Create pause custom resouce action 

### ISSUE THREAD

**Issue by xdevxy** [numaproj/numaplane#293]
# Summary

To support pause via ArgoCD UI extension, we need to add pause [custom resource action](https://argo-cd.readthedocs.io/en/stable/operator-manual/resource_actions/#custom-resource-actions) and additional project [RBAC](https://argo-cd.readthedocs.io/en/stable/operator-manual/rbac/#the-action-action) .

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by dpadhiar** [comment]
Completed as https://github.com/argoproj/argo-cd/pull/20128 has been merged.
