### ISSUE TITLE
e2e Debuggability - Pods directory doesn't seem to have all of the Pods

### ISSUE THREAD

**Issue by juliev0** [numaproj/numaplane#301]
**Describe the bug**

Both in the CI and on my local machine, I have seen not all Pods exist in `tests/e2e/resources/pipelinerollouts/pods` for some reason.

Locally, I just ran the test and failed it [here](https://github.com/numaproj/numaplane/blob/main/tests/e2e/functional_test.go#L398) (this line is not commented out in my branch). And my `tests/e2e/resources/pipelinerollouts/pods` directory is empty.

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We often sort issues this way to know what to prioritize.

**Comment by juliev0** [comment]
Note that my branch is fairly up to date with main:

```
commit 819afa2d6efd18e5f3275db57dfaff419b36037a (origin/main, origin/HEAD)
Author: Dillen Padhiar <38965141+dpadhiar@users.noreply.github.com>
Date:   Thu Sep 26 11:01:25 2024 -0700

    test: e2e debuggability improvements (#297)
    
    Signed-off-by: Dillen Padhiar <dillen_padhiar@intuit.com>
```

**Comment by dpadhiar** [comment]
Looking into this
