### ISSUE TITLE
MonoVertex pods often unhealthy in e2e test

### ISSUE THREAD

**Issue by juliev0** [numaproj/numaplane#314]
**Describe the bug**
I'm not sure that this is any issue on our side, but would be worth investigating. Ultimately, could be something to hand over to Numaflow team to look at after some analysis on our side.

I was seeing that the MonoVertex pod was in a crash loop at the very end of the e2e test. I'm not sure if it's consistent or not, but I've seen it more than once. (Perhaps it's okay and it eventually fixes itself?)

This is the CI log from the test I ran locally:
[ci.log.txt](https://github.com/user-attachments/files/17219806/ci.log.txt)
These are the outputs from `tests/e2e/outputs` directory:
[output.zip](https://github.com/user-attachments/files/17219787/output.zip)

If you look at `outputs/resources/monovertexrollouts/pods` you can see many Pods in there, which seems to indicate that the Pods restarted a lot. 

**To Reproduce**

1. DATA_LOSS_PREVENTION=true make start
2. DATA_LOSS_PREVENTION=true make test-e2e 

I assume this also happens for DATA_LOSS_PREVENTION=false, but I didn't try it.

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We often sort issues this way to know what to prioritize.

**Comment by juliev0** [comment]
Hey @chandankumar4 - I unassigned this from you. Instead, I'll try running it again and since Sidhant has now run our e2e himself locally, he could be the one to look at it if it's occurring.

**Comment by juliev0** [comment]
Hey @dpadhiar - not super high priority, but would be good to fix the e2e test so that after updating MonoVertexRollout, the MonoVertex Pod is not in a crash loop (see log above)

**Comment by dpadhiar** [comment]
> Hey @dpadhiar - not super high priority, but would be good to fix the e2e test so that after updating MonoVertexRollout, the MonoVertex Pod is not in a crash loop (see log above)

I see, looks like the version I change the upgrade to (from stable to 0.6.0) causes an issue. Will change that soon.
