### ISSUE TITLE
Lua script: PipelineRollout in "Pending" state should indicate "Progressing", not "Suspended" in ArgoCD

### ISSUE THREAD

**Issue by juliev0** [numaproj/numaplane#343]
**Describe the bug**
Our Lua script looks for Pause conditions and if true, calls the PipelineRollout "suspended", but "progressing" may be more appropriate. 

Note that if PipelineRollout has not yet deployed the new Pipeline because it's pausing it first, the PipelineRollout phase=Pending. 

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We often sort issues this way to know what to prioritize.

**Comment by juliev0** [comment]
FYI, I confirmed when running, that if we do an update on the Pipeline, it will indicate "Suspended" for a period of time. This is okay but seems like "Progressing" would make more sense?

**Comment by vigith** [comment]
> FYI, I confirmed when running, that if we do an update on the Pipeline, it will indicate "Suspended" for a period of time. This is okay but seems like "Progressing" would make more sense?

Yes, "progressing" is the right terminology.

**Comment by juliev0** [comment]
Looking at all 4 of the Rollouts, this is what I have in mind:

If any are `phase=Pending`, result should be "Progressing". 
For PipelineRollout and ISBServiceRollout, they have `Status.UpgradeInProgress` field. If this is not "", result should be "Progressing". 

Also, currently we look at the `ObservedGeneration` of the Conditions. I may be wrong, but I personally think this isn't necessary - if a Condition indicates we're paused or unhealthy, we shouldn't need to also verify the "ObservedGeneration" of the Condition in order to believe it's true. After all, we are already verifying that the overall "ObservedGeneration" of the CR matches the "Generation", which tells us whether we've reconciled the last update. I feel that verifying the "ObservedGeneration" of the Condition makes the logic more complicated and more prone to bugs.

**Comment by juliev0** [comment]
Assigning this to myself since I have specific preferences :)
