### ISSUE TITLE
Configure SyncPeriod

### ISSUE THREAD

**Issue by juliev0** [numaproj/numaplane#388]
# Summary

Reconciliations normally occur through:

- a change to a Watched resource in the informer cache
- a call we made to RequeueAfter to queue after some period of time

In addition, it will still be good to have a fail safe to ensure we reconcile every resource at some minimum regularity. [This](https://akashjain971.medium.com/part-1-configure-reconcile-frequency-4a000b98cb0#:~:text=Though%20Kubernetes%20is%20designed%20to,after%20the%20object%20is%20processed) article how to configure that. Note the default is 10 hours, and I believe we should make it more frequent than that. At this point, I would say once every 15 minutes.

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by juliev0** [comment]
I have attempted [this](https://github.com/numaproj/numaplane/pull/432/files) but I'm not sure why it's not working

**Comment by chandankumar4** [comment]
After doing some debugging and research, I landed on this [issue](https://github.com/kubernetes-sigs/controller-runtime/issues/2355) from controller-runtime which is exactly our problem is, as per mentioned in the issue I have tried removing the predicate filter and set SyncPeriod to 2min and it worked as expected, I see in numaplane log which is reconciling every 2min.
