### ISSUE TITLE
Deprecation of `spec.lifecycle.deleteGracePeriodSeconds` in Pipeline

### ISSUE THREAD

**Issue by whynowy** [numaproj/numaplane#422]
# Summary

Updated to `spec.lifecycle.deletionGracePeriodSeconds`, make corresponding changes if it's needed. 

https://github.com/numaproj/numaflow/pull/2226

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by juliev0** [comment]
this field isn't used anywhere in our code so I believe I can close this
