### ISSUE TITLE
PipelineRollout to incorporate pausing/paused into its Status

### ISSUE THREAD

**Issue by xdevxy** [numaproj/numaplane#72]
# Summary

We will configure for ArgoCD how to use each of our CRD's Status fields to return a unique HealthStatus field based on the values. One of ArgoCD's HealthStatuses is called "HealthStatusSuspended". 

We need to be able to reflect that our Pipeline's Status is "pausing" or "paused" in the health status.

TBD on how to best do this. We may or may not want to change our current `ChildResourcesHealthy` condition. 

# Use Cases

When a pipeline is in pausing/paused and other state, it should be reflected through PipelineRollout status as well.

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by juliev0** [comment]
Since it's a Condition set to true/false, we should consider it no longer being a Condition in that case but maybe a separate field in Status?

**Comment by juliev0** [comment]
@afugazzotto I believe you already took care of this one, right?

**Comment by afugazzotto** [comment]
> @afugazzotto I believe you already took care of this one, right?

Yes, we should use the condition `ConditionPipelinePausingOrPaused` https://github.com/numaproj/numaplane/blob/main/pkg/apis/numaplane/v1alpha1/pipelinerollout_types.go#L26

**Comment by juliev0** [comment]
And it looks like not only did you create the Condition but you're also [setting it](https://github.com/numaproj/numaplane/blob/main/internal/controller/pipelinerollout_controller.go#L296), so I am closing this issue.

**Comment by afugazzotto** [comment]
> And it looks like not only did you create the Condition but you're also [setting it](https://github.com/numaproj/numaplane/blob/main/internal/controller/pipelinerollout_controller.go#L296), so I am closing this issue.

Yes, but the LUA script for ArgoCD will need to use that condition. I assume we have another issue to track work on LUA script since your are closing this.

**Comment by juliev0** [comment]
> > And it looks like not only did you create the Condition but you're also [setting it](https://github.com/numaproj/numaplane/blob/main/internal/controller/pipelinerollout_controller.go#L296), so I am closing this issue.
> 
> Yes, but the LUA script for ArgoCD will need to use that condition. I assume we have another issue to track work on LUA script since your are closing this.

Yes, this one: https://github.com/numaproj/numaplane/issues/29
I'll clarify there that we want to incorporate pausing into the ArgoCD health check
