### ISSUE TITLE
Numaplane Docker images have security vulnerabilities

### ISSUE THREAD

**Issue by juliev0** [numaproj/numaplane#82]
**Describe the bug**
quay.io seems to indicate that our image has vulnerabilities

See the "dev-release-automation" image [here](https://quay.io/repository/numaproj/numaplane-controller?tab=tags) which is the branch I tested release automation on (in [this](https://github.com/numaproj/numaplane/pull/81) PR)

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We often sort issues this way to know what to prioritize.

**Comment by juliev0** [comment]
@shubhamdixit863 have you already started working on this? I was assuming you hadn't, so I unassigned it from you as I've instead assigned you some other internal issues. Let me know, thanks!

**Comment by juliev0** [comment]
@xdevxy not sure if you want to continue looking at it? I assigned it back to you if so

**Comment by xdevxy** [comment]
I unassigned myself for now
