### ISSUE TITLE
Consider whether we need support minimal CRD installation

### ISSUE THREAD

**Issue by xdevxy** [numaproj/numaplane#84]
# Summary

As numaflow support minimal CRD installation, we'd like to consider if numaplane needs to do the same.

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by juliev0** [comment]
seems like you are doing this now?

**Comment by juliev0** [comment]
it seems like if we don't see a need, we could just close this until a need arises in the future, if it ever does
