### ISSUE TITLE
Support no down time Numaflow Controller Upgrade

### ISSUE THREAD

**Issue by xdevxy** [numaproj/numaplane#87]
# Summary

We need to support no down time Numaflow Controller Update without data loss.

# Use Cases

Upgrade with downtime is not ideal with production pipelines.

- [x] #183
- [x] #225 
- [ ] #321

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by juliev0** [comment]
We still have the child issue - I'm going to close this parent issue since I don't think we necessarily need it
