### ISSUE TITLE
Pause all Pipelines on the namespace prior to updating a Controller/ISBService 

### ISSUE THREAD

**Issue by juliev0** [numaproj/numaplane#9]
Document [here](https://docs.google.com/document/d/1xHzzaH8DgE9rxo_xCnbeWDmW49THgXQ8yDiOReb5edU/edit). Note that we may need to check the [status](https://github.com/numaproj/numaflow/issues/1773) of Numaflow-Controller deployment to see if latest change has being reconciled before resuming the pipelines.

**Comment by xdevxy** [comment]
https://github.com/numaproj/numaplane/issues/124 can be an enhancement after this is done
