### ISSUE TITLE
Tests Reusability

### ISSUE THREAD

**Issue by afugazzotto** [numaproj/numaplane#99]
# Summary

Improve test reusability by:
- creating functions that can be reused between test cases
- create test cases that can be reused between the 3 controllers test "suites"
- create test cases, suites, functions that can be reused between E2E and Unit Tests

# Use Cases

Reduce code duplication and create future test cases that can be applied more easily to multiple controllers and on both Unit Tests and E2E tests (as appropriate).

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by juliev0** [comment]
I've created reusable functions for the e2e test. For the unit tests, I think we should replace the existing framework in which an entire struct is considered a "unit" with tests in which the function is the "unit". I was starting to do this for the PipelineRolloutReconciler as part of the pause feature. 

Do we still need this issue open in that case?

**Comment by xdevxy** [comment]
Let's close this, and reopen if needed
